# Prompt format
format = """
$directory\
$git_branch\
$git_status\
$character
"""

# Inserts a blank line between shell prompts
add_newline = false

# Prompt config
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold green)"

[git_branch]
#style = "bold yellow"
style = "#808080"
format = "[$symbol$branch]($style) "

[git_status]
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
stashed = ""
untracked = "? "
staged = "+ "
modified = "! "
conflicted = "!= "
renamed = "» "
deleted = "✘ "
style = "bold yellow"
format = "([$all_status$ahead_behind]($style))"
