# Prompt format
format = """
$directory\
$git_branch\
$git_status\
$character
"""

# Inserts a blank line between shell prompts
add_newline = false
# Waits for commands before executing
command_timeout = 1000

# Prompt config
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold green)"

[git_branch]
style = "#808080"
format = "[ $branch]($style) "

[git_status]
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
stashed = ""
untracked = "? "
staged = "+ "
modified = "* "
conflicted = "!= "
renamed = " "
deleted = " "
style = "bold yellow"
format = "([$all_status$ahead_behind]($style))"
